build: fix sass compilation error (#10806)
Fixes the following SASS error due to a top-level ampersand selector:

```
Error in plugin 'sass'
Message:
    src\lib\core\_core.scss
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 43 of src/lib/core/_core.scss, in mixin `mat-core-theme`
        from line 39 of src/lib/core/theming/_all-theme.scss, in mixin `angular-material-theme`
        from line 14 of src/lib/core/theming/prebuilt/deeppurple-amber.scss
>>   &.mat-app-background {

   --^
```