build: bazel ts-api-guardian usage fails on workspaces which don't depend on `chalk`
When using the npm package in a workspace which doesn't depend on chalk, ts-api-guardian fails with an error `Error: Cannot find module 'chalk'`