fix(animations): Fix "'hasOwnProperty' of undefined" crash
Fix random crashes with:

    TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Array.forEach (native)
    at e.init
    at t.e._queuePlayer
    at t.e.animateTransition
    ...

This commit fixes #16470 and closes #15858 (which has been abandoned
for a while).