build(docs-infra): update the dependency versions of the examples
On OS/X The examples were failing to build due to a version mismatch
with fsevents that results in errors that look like:

```
$ ng serve
...
/.../angular/aio/tools/examples/shared/node_modules/chokidar/lib/fsevents-handler.js:28
  return (new fsevents(path)).on('fsevent', callback).start();
          ^
TypeError: fsevents is not a constructor
    at createFSEventsInstance (/.../angular/aio/tools/examples/shared/node_modules/chokidar/lib/fsevents-handler.js:28:11)
    at setFSEventsListener (/.../angular/aio/tools/examples/shared/node_modules/chokidar/lib/fsevents-handler.js:82:16)
    ...
error Command failed with exit code 1.
```

This commit updates the `@angular-devkit/build-angular` dependency to fix
this problem.