build(packaging): Use natives v1.1.6
Add manual resolution for natives v1.1.6 because the current resolved
version 1.1.4 does not work with Node v10.14.2

Error: ReferenceError: internalBinding is not defined

See issue https://github.com/gulpjs/gulp/issues/2246