Fix TypeScript 1.6.2 compiler error TS2345
Missing `pipes` property in `ViewFactory` cause following error:
```
error TS2345: Argument of type '{ selector: string; }' is not assignable to parameter of type '{ pipes: any[]; selector?: string; properties?: string[]; events?: string[]; host?: StringMap<str...'.  
Property 'pipes' is missing in type '{ selector: string; }'.
```