fix(bazel): pin terser to 4.4.0
4.4.1 caused a regression https://github.com/terser/terser/issues/527 which is breaking our CI with such errors:
```
http://localhost:4200/main.57ce335e666ac98d65ad.js 0:370275 TypeError: e is not a function
```

Example of failing build https://circleci.com/gh/angular/angular/549169?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link