ci: temporarily disable compiler tests on windows
`//packages/compiler/test` tests are intermittently failing with the error below:

```
Error: Errors from TypeScript:
Cannot write file '/node_modules/@angular/core/core.ngfactory.d.ts' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.
```

This only happens on the Windows Codefresh CI track.

We're not sure why, but it doesn't always happen. Currently we suspect it's related the the implicit caching model in Codefresh surfacing a problem in our setup.