fixup! build: update cross-repo angular dependencies
Update browserslists db. The update of Angular CLI caused
a mismatch of browserslist databases and resulted in errors like:

```
BrowserslistError: [BABEL] /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/sandbox/processwrapper-sandbox/997/execroot/angular/bazel-out/k8-fastbuild/bin/aio/node_modules/css-loader/dist/runtime/sourceMaps.js: Unknown version 109 of edge (While processing: "base$0$0")
```