ci: update to latest version of dev-infra actions
This resolves

```
ERROR: java.io.IOException: Error getting access token for service account: 400 Bad Request
{"error":"invalid_grant","error_description":"Invalid JWT Signature."}
```