postinstall script missing map output file name
$ node tools/cli-patches/patch.js && uglifyjs node_modules/lunr/lunr.js -c -m -o
 src/assets/js/lunr.min.js --source-map
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer